#!/usr/bin/env python
# encoding: utf-8
"""
TODO

Created by Jacob Kristhammar on 2011-03-14.
"""

import glob
import optparse
import os
import shutil
import sys
import time


ARCHIVE_FORMAT_DEFAULT = "%Y-%m_archive"


def main():
	print 1
	usage = "usage: %%prog [options] absolute_path_to_folder"
	parser = optparse.OptionParser(usage=usage)
	parser.add_option("-f", "--format", type="string", dest="format",
	                  help="format of archived folder named", 
		  			  metavar="python strftime format string",
	                  default=ARCHIVE_FORMAT_DEFAULT)

	(options, args) = parser.parse_args()

	if len(args) != 1:
	    parser.print_usage()
	    sys.exit(1)

	path = args.pop()
	expanded_path = os.path.expanduser(path)

	if not os.path.isabs(expanded_path):
		print "path not absolute"
		sys.exit(1)

	if not os.path.exists(expanded_path):
		print "folder doesn't exists"
		sys.exit(1)

	print "collecting files"	
	debree = []
	for f in os.listdir(expanded_path):
		try:
			time.strptime(f, options.format)
		except ValueError:
			debree.append(f)

	archive_name = time.strftime(options.format)
	archive_folder = os.path.join(expanded_path, archive_name)
	if os.path.exists(archive_folder):
		print "warning: archive already exists"
	else:
		print "creating archive %s" % archive_name
		os.mkdir(archive_folder)
	
	print "moving files to archive"
	for f in debree:
		absolute_file = os.path.join(expanded_path, f)
		print "archiving %s" % absolute_file
		try:
			shutil.move(absolute_file, archive_folder)
		except Exception, e:
			print "failed to archive %s" % f
	
	print "done!"


if __name__ == '__main__':
    main()

